name: DNSForwarder
main: com.github.suprememortal.dnsforwarder.DNSForwarder
version: "${pom.version}"
api: ["1.0.0"]
author: SupremeMortal
description: Forward players to a specific server from a mapped DNS address.
website: https://github.com/SupremeMortal/DNSForwarder
commands:
  reloaddns:
    description: "Reload DNSForwarder config"
    permission: "command-reloaddns"
permissions:
  command-reloaddns:
    default: op
